### ISSUE TITLE
MongoDb with Nightscout 

### ISSUE THREAD

**Issue by Tony10ajf** [dhermanns/rpi-nightscout#1]
Working through the instructions on Nightscout with a Raspberry PI 1 it is not clear how to load the MongoDb.  It's identified as a requirement on the ReadMe but is not clear in the set of procedures below that.  When I run the docker logs it is clear that there is no connection possible to the MongoDb.  Any assistance welcome.

**Comment by dhermanns** [comment]
Hi Tony!

This the magic that docker-compose does for you. The docker-compuse up -d pulls the mongo db and links it to your nightscout backend. You should see a running mongo db afterwards when entering a "docker ps" afterwards.

But maybe you would like to switch to raspberry 2 if possible. I didn't test it on Pi1 for a long time, since I doesn't own one anymore...
