### ISSUE TITLE
https

### ISSUE THREAD

**Issue by JoebartOOn** [dhermanns/rpi-nightscout#21]
Good evening,
Can you explain to me how to switch to https? It's not very clear to me and I have nightscout running smoothly on an rpi 4 with ssd but I'm stuck without https. (no nightscout reporter, no M5stack and lots of other stuff)
Thank you in advance for your help.

**Comment by dhermanns** [comment]
Hi!

I'm not using node anymore for the TLS (https) termination. This is because the certificate generation was
very poorly supported since I tried the last time.

What runs fine for me is using the nginx as a reverse proxy. Nginx is supported very well from letsencrypt.
It generates certificates on your behalf.

I configured it on my raspberry by using this tutorial:
https://blog.doenselmann.com/nginx-und-lets-encrypt-auf-raspberry-pi/

Maybe it's useful for you.

**Comment by JoebartOOn** [comment]
Hi,

Thank you for the link.
So I created a domain name for myself and followed the tutorial. I got the
positive message that the letsencrypt certificate is obtained.
What should I do next? I am a little lost...
Thank you in advance for your help.

**Comment by dhermanns** [comment]
The tutorial describes all steps you need. If you already setup everything, you should have an nginx that redirects to your rpi-nightscout docker container. So you should be able to call your configured domain.
